### ISSUE TITLE
Allow authentication using Azure Storage Account SAS

### ISSUE THREAD

**Issue by danield137** [Azure/azure-storage-queue-go#14]
Hi, I'm trying to achieve a similar functionality to what we have in python [here](https://github.com/Azure/azure-kusto-python/blob/725130623fa4a97bc657cb1282d89cc34efcd5bc/azure-kusto-ingest/azure/kusto/ingest/_ingest_client.py#L113)

```python
storage_client = CloudStorageAccount(account_name, sas_token=sas)
queue_service = storage_client.create_queue_service()
```

I couldn't find a way to do so.

**Comment by JeffreyRichter** [comment]
In the new client libraries, SAS is not a credential type. You use Anonymous credentials when you want to use a SAS and then you just put the SAS query parameters on the URL. So, new up a Pipeline with Anonymous credentials, then call azqueue.NewServiceURL passing the desired URL with the SAS query parameters in the URL and the pipeline.

**Comment by zezha-msft** [comment]
@danield137 please refer to this [sample](https://github.com/Azure/azure-storage-queue-go/blob/master/azqueue/zt_examples_test.go#L333).
