### ISSUE TITLE
Provide an example using SAS Key

### ISSUE THREAD

**Issue by shrutir25** [Azure/azure-storage-queue-go#15]
It would be very helpful to see an example of operations with the queue using an existing SAS Key. I see comments stating that we can create credentials using `NewAnonymousCredential` function, but I don't see any steps on how to proceed.

**Comment by zezha-msft** [comment]
Hi @shrutir25, please refer to the sample [here](https://github.com/Azure/azure-storage-queue-go/blob/master/azqueue/zt_examples_test.go#L419).
