### ISSUE TITLE
Segfault error when updating MessageURL

### ISSUE THREAD

**Issue by lttito** [Azure/azure-storage-queue-go#16]
I've encountered this error in our system:
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x863889]`
 
`goroutine 52 [running]:
github.com/Azure/azure-storage-queue-go/azqueue.MessageIDURL.Update(0xc0000271d0, 0x5, 0x0, 0x0, 0x0, 0xc0000271d8, 0x27, 0xc0000d1b30, 0x45, 0x0, ...)
    /go/pkg/mod/github.com/!azure/azure-storage-queue-go@v0.0.0-20190416192124-a17745f1cdbf/azqueue/url_messageid.go:51 +0x129`

As a suggestion, I saw in [code](https://github.com/Azure/azure-storage-queue-go/blob/master/azqueue/url_messageid.go) that on [line 47](https://github.com/Azure/azure-storage-queue-go/blob/a17745f1cdbfe1a3a73c62ec07756ae82754c61a/azqueue/url_messageid.go#L47), r is calculated and then used on [line 51](https://github.com/Azure/azure-storage-queue-go/blob/a17745f1cdbfe1a3a73c62ec07756ae82754c61a/azqueue/url_messageid.go#L51). I think r can be nil and could throw this error when on [line 51](https://github.com/Azure/azure-storage-queue-go/blob/a17745f1cdbfe1a3a73c62ec07756ae82754c61a/azqueue/url_messageid.go#L51) `PopReceipt(r.PopReceipt())` is done. Maybe checking if r is nil before using it on [line 51](https://github.com/Azure/azure-storage-queue-go/blob/a17745f1cdbfe1a3a73c62ec07756ae82754c61a/azqueue/url_messageid.go#L51) can solve the issue.

**Comment by zezha-msft** [comment]
Thanks @lttito for reaching out!

@adreed-msft could you please take a look?

**Comment by adreed-msft** [comment]
It was down to a lack of error checking. We basically assumed R wouldn't be nil even if there was an error.

**Comment by zezha-msft** [comment]
Fixed in 0.3.
