### ISSUE TITLE
Provide simplified approach for different Azure clouds

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-storage-queue-go#25]
Provide simplified approach for different Azure clouds similar to .NET SDK where you can define the type of cloud and it will return the respective endpoints for authentication, etc.

We want to support storage for all clouds and are now using endpoint suffixes but ideally we just define the type of cloud and it resolves the endpoint suffix for us.

**Comment by tomkerkhove** [comment]
Relates to https://github.com/kedacore/keda/pull/1863

**Comment by amirschw** [comment]
Found it in Azure/go-autorest: https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go

**Comment by tomkerkhove** [comment]
That'd exactly what I meant, thanks!

**Comment by zezha-msft** [comment]
@tomkerkhove thanks for reaching out!

As far as I know, all the Storage SDKs are consistent in the way that it accepts an endpoint explicitly. 

Is the package posted by @amirschw sufficient for your use case? If yes please close this issue, thanks!

**Comment by tomkerkhove** [comment]
We went that route, thanks.
