### ISSUE TITLE
MessagesClearResponse does not populate with on Server Time out

### ISSUE THREAD

**Issue by sandeepkru** [Azure/azure-storage-queue-go#6]
https://github.com/Azure/azure-storage-queue-go/blob/cd780c609833a241f2c43999f959a586c6d814a8/2017-07-29/azqueue/url_messages.go#L69

`MessagesClearResponse` here doesn't seem to be returning correctly, I observed that it returned `nil` and below is the fatal message. I didn't debug further, it seems bug to me.

```console
 --------------------------------------------------------------------------------
   RESPONSE Status: 500 Operation could not be completed within the specified time.
   Content-Length: [245]
   Content-Type: [application/xml]
   Date: [Thu, 27 Sep 2018 22:08:42 GMT]
   Server: [Windows-Azure-Queue/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [OperationTimedOut]
   X-Ms-Request-Id: [7bc6161d-b003-0013-0bae-5651e1000000]
   X-Ms-Version: [2017-07-29]
```

**Comment by JeffreyRichter** [comment]
If the Clear method fails, then the *MessagesClearResponse should be nil but the returned error should not be nil. So, based on what you are saying, the existing behavior is by-design and seems to be working correctly.

**Comment by sandeepkru** [comment]
My bad please close this, I believe `error` wasn't indicating `OperationTimedOut` but I'm not able to repro this now.
