### ISSUE TITLE
Lack of interfacing prevents use of mocking

### ISSUE THREAD

**Issue by bredr** [Azure/azure-storage-queue-go#7]
Typically when you have a `New*` function you might expect to return an interface rather than a struct directly. This allows for developers to mock dependencies such as this package in order to unit test their integration. The current implementation of this package lacks such interfaces for example for `NewMessageIDURL`.  Please can this be considered for future versions.

**Comment by JeffreyRichter** [comment]
We did think about mocking. Specifically, our SDKs make use of a pipeline architecture where a pipeline is an ordered collection of policies. Each policy can mutate an HTTP request and/or response or can modify its behavior in some way. So, YOU could create your own policy and insert it into a pipeline and then your policy can alter the behavior (do mocking). For information, see https://godoc.org/github.com/Azure/azure-pipeline-go/pipeline. 

We're open to feedback on how well this works for you and if there is something we could do to improve the mocking experience.

**Comment by JeffreyRichter** [comment]
Here's another thought on this: in Go, types implement interfaces implicitly and so YOU can define the interface yourself and the type the SDK exposes will simply implement it. Then YOU can create your own mock type that also implements the interface and viola! You have implemented your own mocking infrastructure.
